package entitypack;

public enum Frame {
    MAINMENU,
    CREATEUSERACCOUNT,
    LOGIN,
    TRADINGUSERACTIONSMENU,
    ADMINACTIONSMENU,
    BROWSINGUSERACTIONSMENU,
    VIEWALLOTHERUSERSMENU,
    VIEWUSERMENU,

    MESSAGEALERT,
    FREEZEUSERALERT,
    FROZENALERT,
    ITEMVALIDATIONDECLINEDALERT,
    ITEMVALIDATIONREQUESTALERT,
    REPORTALERT,
    TRADEACCEPTEDALERT,
    TRADECANCELLEDALERT,
    TRADEDECLINEDALERT,
    TRADEPASTDATEALERT,
    TRADEREQUESTALERT,
    TRADEREQUESTCANCELLEDALERT,
    UNFREEZEREQUESTALERT




}
