package entitypack;

public enum Frame {
    MAINMENU,
    CREATEUSERACCOUNT,
    LOGIN,
    TRADINGUSERACTIONSMENU,
    ADMINACTIONSMENU,
    BROWSINGUSERACTIONSMENU,
    VIEWALLOTHERUSERSMENU,
    VIEWUSERMENU,

    EXPIRATIONALERT,
    MESSAGEALERT,
    FREEZEUSERALERT,
    FROZENALERT,
    ITEMVALIDATIONDECLINEDALERT,
    ITEMVALIDATIONREQUESTALERT,
    REPORTALERT,
    TRADEACCEPTEDALERT,
    TRADECANCELLEDALERT,
    TRADEDECLINEDALERT,
    TRADEPASTDATEALERT,
    TRADEREQUESTALERT,
    TRADEREQUESTCANCELLEDALERT,
    UNFREEZEREQUESTALERT,

    TRADETOSTRING,

    VIEWPENDINGTRADESMENU,
    VIEWUSERSTATSMENU,

    VIEWITEMSANDWISHLISTMENU,

    SETACTIVESTATUSMENU,

    CREATEITEMVALIDATIONREQUESTMENU,

    SETACTIVECITYMENU,
    SENDTRADEREQUESTMENU,
    VIEWITEMVALIDATIONREQUESTS,

    SENDMESSAGEMENU,
    THRESHOLDSMENU,

    ADDNEWADMIN,
    ADMINVIEWTRADE,
    ADMINVIEWUSER,
    EDITTRADE,
    ADMINFREEZE,

    ACCEPTTRADEMENU,
    CONFIRMTRADEMENU,
    SUGGESTTRADE,
    CONFIRMREEXCHANGEMENU,

    ADDITEMTOWISHLISTMENU,
    VIEWCURRENTTHRESHOLDS,
    ITEMVIEWER,
    REMOVEFROMINVENTORY,
    ;

}
